services:
  2004scape:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8888:8888
      - 43594:43594
      - 43500:43500
      - 43501:43501
      - 45099:45099
