name: Verify Content

on:
  pull_request:
  push:
    paths:
    - '.github/workflows/content.yml'
    - 'data/src/**'
  workflow_dispatch:


jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - run: bun install

    - name: Pack
      run: bun run build
